[build]
  command = "npm ci --legacy-peer-deps --include=dev && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22.16.0"
  NPM_VERSION = "10.8.2"
  CI = "true"

# Development server configuration
[dev]
  targetPort = 8888  # Tell Netlify Dev to look for Vite on port 8888
  # Ensure proper MIME types for module scripts
  autoLaunch = false  # Prevent auto-opening browser to avoid conflicts
  # Force proper MIME type handling
  framework = "#custom"
  command = "npm run dev"

# Redirects for SPA and API endpoints - API only
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Ensure frontend assets are served by Vite with correct MIME types
[[redirects]]
  from = "/src/*"
  to = "/src/:splat"
  status = 200
  force = false  # Let Vite handle these

# CRITICAL: Let Vite handle its internal modules directly - bypass Netlify proxy
[[redirects]]
  from = "/@vite/*"
  to = "/@vite/:splat"
  status = 200
  force = false  # Let Vite handle these completely



# NIP-05 verification - serve .well-known directory
[[redirects]]
  from = "/.well-known/*"
  to = "/.well-known/:splat"
  status = 200
  force = true

# Dynamic NIP-05 API endpoint
[[redirects]]
  from = "/.well-known/nostr.json"
  to = "/.netlify/functions/nostr"
  status = 200
  force = true

# SPA redirects - all non-API routes go to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    
    # Content Security Policy for Bitcoin-only, privacy-first app
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://unpkg.com https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://*.supabase.co https://*.netlify.app wss://*.supabase.co; frame-src 'none'; object-src 'none'; base-uri 'self'; form-action 'self';"
    
    # CORS headers for API
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    Access-Control-Max-Age = "86400"

# API-specific headers
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With, X-CSRF-Token"
    Access-Control-Max-Age = "86400"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"

# ES Module files (.mjs) MIME type - for Vite internal files
[[headers]]
  for = "/@vite/*"
  [headers.values]
    Content-Type = "application/javascript"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/@vite/client/env.mjs"
  [headers.values]
    Content-Type = "application/javascript"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "**/*.mjs"
  [headers.values]
    Content-Type = "application/javascript"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "*.mjs"
  [headers.values]
    Content-Type = "application/javascript"
    X-Content-Type-Options = "nosniff"

# Static assets caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Service worker caching
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"

# Environment-specific settings
[context.production]
  [context.production.environment]
    NODE_ENV = "production"
    VITE_API_BASE_URL = "/.netlify/functions"

[context.deploy-preview]
  [context.deploy-preview.environment]
    NODE_ENV = "preview"
    VITE_API_BASE_URL = "/.netlify/functions"

[context.branch-deploy]
  [context.branch-deploy.environment]
    NODE_ENV = "development"
    VITE_API_BASE_URL = "/.netlify/functions"

# Functions configuration
[functions]
  # Node.js version for functions
  node_bundler = "esbuild"
  external_node_modules = ["pg", "redis", "jsonwebtoken"]

# Force ESM format for all functions
[functions."*"]
  node_bundler = "esbuild"

  # Scheduled functions for cleanup tasks
  [functions.scheduled]
    cleanup-expired-credentials = "0 */6 * * *"  # Run every 6 hours