-- OTS/SimpleProof Integration — Agent Attestation Storage
-- Migration: 20260322_ots_simpleproof_integration
-- Purpose: Extend agent_profiles with OTS proof storage and SimpleProof API key fields
-- Aligned with: docs/specs/OTS-SIMPLEPROOF-INTEGRATION.md (to be created)
-- Related: NIP-SKL attestations (kind 1985), NIP-SA agent state, NIP-AC settlement receipts

-- ============================================================================
-- EXTEND AGENT_PROFILES TABLE WITH OTS/SIMPLEPROOF FIELDS
-- ============================================================================

-- OTS Proof Storage
ALTER TABLE agent_profiles
  ADD COLUMN IF NOT EXISTS ots_proofs_storage_url TEXT;

COMMENT ON COLUMN agent_profiles.ots_proofs_storage_url IS
  'URL/path where agent''s OpenTimestamps .ots proof files are stored (e.g. Supabase Storage bucket, IPFS CID, or agent-controlled endpoint)';

-- SimpleProof API Integration (future)
ALTER TABLE agent_profiles
  ADD COLUMN IF NOT EXISTS simpleproof_api_key_encrypted TEXT;

COMMENT ON COLUMN agent_profiles.simpleproof_api_key_encrypted IS
  'Encrypted SimpleProof API key for agent-independent proof generation (encrypted via ClientSessionVault pattern)';

ALTER TABLE agent_profiles
  ADD COLUMN IF NOT EXISTS simpleproof_enabled BOOLEAN DEFAULT false;

COMMENT ON COLUMN agent_profiles.simpleproof_enabled IS
  'Feature flag: true if agent has SimpleProof integration enabled';

-- OTS Attestation Metrics
ALTER TABLE agent_profiles
  ADD COLUMN IF NOT EXISTS ots_attestation_count INTEGER DEFAULT 0;

COMMENT ON COLUMN agent_profiles.ots_attestation_count IS
  'Total number of OpenTimestamps proofs generated by this agent';

ALTER TABLE agent_profiles
  ADD COLUMN IF NOT EXISTS last_ots_attestation_at TIMESTAMPTZ;

COMMENT ON COLUMN agent_profiles.last_ots_attestation_at IS
  'Timestamp of most recent OTS proof generation by this agent';

-- ============================================================================
-- OTS PROOF RECORDS TABLE
-- ============================================================================
-- Stores metadata for all OTS proofs generated by agents
-- The actual .ots proof files are stored externally (Supabase Storage, IPFS, etc.)

CREATE TABLE IF NOT EXISTS ots_proof_records (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  proof_hash             TEXT NOT NULL UNIQUE,   -- SHA-256 hash of attested data
  ots_proof_file_url     TEXT NOT NULL,          -- URL to .ots proof file
  bitcoin_block_height   INTEGER,                -- Bitcoin block height where proof is anchored
  attestation_timestamp  TIMESTAMPTZ DEFAULT NOW(),
  agent_pubkey           TEXT NOT NULL,          -- Agent who created this proof
  nostr_event_id         TEXT,                   -- NIP-03 kind 1040 event id (if published)
  simpleproof_proof_id   TEXT,                   -- SimpleProof platform proof ID (future)
  
  -- Link to attested Nostr event (if applicable)
  attested_event_kind    INTEGER,                -- e.g. 1985 (attestation), 39201 (agent state), 39244 (settlement)
  attested_event_id      TEXT,                   -- Nostr event id being timestamped
  
  -- Proof status
  proof_status           TEXT CHECK (proof_status IN ('pending','confirmed','failed'))
                         DEFAULT 'pending',
  confirmed_at           TIMESTAMPTZ,            -- When Bitcoin block confirmation occurred
  
  -- Storage metadata
  storage_backend        TEXT CHECK (storage_backend IN ('supabase','ipfs','agent_endpoint','simpleproof'))
                         DEFAULT 'supabase',
  storage_metadata       JSONB DEFAULT '{}',     -- Backend-specific metadata
  
  created_at             TIMESTAMPTZ DEFAULT NOW(),
  updated_at             TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================================
-- INDEXES FOR QUERY OPTIMIZATION
-- ============================================================================

-- Index for agent_pubkey (query all proofs by agent)
CREATE INDEX IF NOT EXISTS idx_ots_proof_records_agent
  ON ots_proof_records(agent_pubkey);

-- Index for attested_event_id (find proof for specific Nostr event)
CREATE INDEX IF NOT EXISTS idx_ots_proof_records_event
  ON ots_proof_records(attested_event_id);

-- Index for proof_status (query pending/confirmed proofs)
CREATE INDEX IF NOT EXISTS idx_ots_proof_records_status
  ON ots_proof_records(proof_status);

-- Index for bitcoin_block_height (query proofs by block)
CREATE INDEX IF NOT EXISTS idx_ots_proof_records_block_height
  ON ots_proof_records(bitcoin_block_height)
  WHERE bitcoin_block_height IS NOT NULL;

-- Composite index for agent + status (common query pattern)
CREATE INDEX IF NOT EXISTS idx_ots_proof_records_agent_status
  ON ots_proof_records(agent_pubkey, proof_status);

-- ============================================================================
-- ROW LEVEL SECURITY (RLS)
-- ============================================================================

ALTER TABLE ots_proof_records ENABLE ROW LEVEL SECURITY;

-- Policy: Agents can SELECT their own proofs
CREATE POLICY ots_proof_records_agent_read
  ON ots_proof_records
  FOR SELECT
  TO authenticated
  USING (agent_pubkey = auth.jwt() ->> 'sub');

-- Policy: Public read for confirmed proofs (audit trail transparency)
CREATE POLICY ots_proof_records_public_read
  ON ots_proof_records
  FOR SELECT
  TO authenticated
  USING (proof_status = 'confirmed');

-- Policy: Service role only for INSERT/UPDATE
-- Rationale: Netlify Functions validate proof data before write
CREATE POLICY ots_proof_records_write
  ON ots_proof_records
  FOR ALL
  TO service_role
  USING (true);

-- ============================================================================
-- TRIGGER: Update updated_at timestamp
-- ============================================================================

CREATE TRIGGER ots_proof_records_updated_at_trigger
  BEFORE UPDATE ON ots_proof_records
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- VERIFICATION QUERY
-- ============================================================================

DO $$
DECLARE
  missing_columns TEXT[] := ARRAY[]::TEXT[];
  col TEXT;
BEGIN
  -- Check OTS/SimpleProof columns in agent_profiles
  FOR col IN
    SELECT unnest(ARRAY[
      'ots_proofs_storage_url',
      'simpleproof_api_key_encrypted',
      'simpleproof_enabled',
      'ots_attestation_count',
      'last_ots_attestation_at'
    ])
  LOOP
    IF NOT EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema = 'public'
        AND table_name = 'agent_profiles'
        AND column_name = col
    ) THEN
      missing_columns := array_append(missing_columns, col);
    END IF;
  END LOOP;

  IF array_length(missing_columns, 1) > 0 THEN
    RAISE EXCEPTION '✗ OTS/SimpleProof columns missing from agent_profiles: %', array_to_string(missing_columns, ', ');
  ELSE
    RAISE NOTICE '✓ All 5 OTS/SimpleProof columns added to agent_profiles';
  END IF;

  -- Check ots_proof_records table exists
  IF EXISTS (
    SELECT 1 FROM pg_tables
    WHERE schemaname = 'public' AND tablename = 'ots_proof_records'
  ) THEN
    RAISE NOTICE '✓ ots_proof_records table created successfully';
  ELSE
    RAISE EXCEPTION '✗ ots_proof_records table creation failed';
  END IF;
END $$;

