-- Agent Task Records LLM Tracking Extension (Phase 1, Task 1.1)
-- Extends agent_task_records table with token tracking and USD cost columns
-- for Adult-role AI agent LLM integration and cost observability
--
-- CHANGES:
-- - Add token tracking columns: input_tokens, output_tokens, total_tokens
-- - Add LLM metadata columns: llm_model, llm_provider
-- - Add USD cost tracking: cost_usd_cents (derived from sats using BTC/USD snapshot)
-- - Add task output summary: task_output_summary (punch-listed deliverables)
-- - Add reporting index: idx_agent_tasks_reporting (assignee_agent_id, completed_at)
--
-- IDEMPOTENCY:
-- - Uses DO $$ blocks with duplicate_column exception handling
-- - Safe to run multiple times
-- - Can be executed directly in Supabase SQL editor
--
-- DEPENDENCIES:
-- - Requires agent_task_records table from 20260213_agent_task_records.sql

-- ============================================================================
-- ADD TOKEN TRACKING COLUMNS
-- ============================================================================

-- Add input_tokens column (tokens sent to LLM)
DO $$ BEGIN
  ALTER TABLE agent_task_records ADD COLUMN input_tokens INTEGER DEFAULT 0;
EXCEPTION WHEN duplicate_column THEN NULL;
END $$;

-- Add output_tokens column (tokens generated by LLM)
DO $$ BEGIN
  ALTER TABLE agent_task_records ADD COLUMN output_tokens INTEGER DEFAULT 0;
EXCEPTION WHEN duplicate_column THEN NULL;
END $$;

-- Add total_tokens column (input + output)
DO $$ BEGIN
  ALTER TABLE agent_task_records ADD COLUMN total_tokens INTEGER DEFAULT 0;
EXCEPTION WHEN duplicate_column THEN NULL;
END $$;

-- ============================================================================
-- ADD LLM METADATA COLUMNS
-- ============================================================================

-- Add llm_model column (e.g., 'gpt-4', 'claude-3-opus')
DO $$ BEGIN
  ALTER TABLE agent_task_records ADD COLUMN llm_model TEXT;
EXCEPTION WHEN duplicate_column THEN NULL;
END $$;

-- Add llm_provider column (e.g., 'openai', 'anthropic')
DO $$ BEGIN
  ALTER TABLE agent_task_records ADD COLUMN llm_provider TEXT;
EXCEPTION WHEN duplicate_column THEN NULL;
END $$;

-- ============================================================================
-- ADD USD COST TRACKING COLUMN
-- ============================================================================

-- Add cost_usd_cents column (derived from actual_cost_sats using BTC/USD snapshot)
-- NOTE: This is DERIVED data, not authoritative. actual_cost_sats remains primary truth.
DO $$ BEGIN
  ALTER TABLE agent_task_records ADD COLUMN cost_usd_cents INTEGER DEFAULT 0;
EXCEPTION WHEN duplicate_column THEN NULL;
END $$;

-- ============================================================================
-- ADD TASK OUTPUT SUMMARY COLUMN
-- ============================================================================

-- Add task_output_summary column (punch-listed deliverables for reporting)
DO $$ BEGIN
  ALTER TABLE agent_task_records ADD COLUMN task_output_summary TEXT;
EXCEPTION WHEN duplicate_column THEN NULL;
END $$;

-- ============================================================================
-- ADD REPORTING INDEX
-- ============================================================================

-- Add index for report queries (assignee_agent_id, completed_at)
-- Used by agent_daily_report and agent_weekly_report views (Phase 4)
DO $$ BEGIN
  EXECUTE 'CREATE INDEX IF NOT EXISTS idx_agent_tasks_reporting ON agent_task_records(assignee_agent_id, completed_at)';
END $$;

-- ============================================================================
-- COMMENTS FOR DOCUMENTATION
-- ============================================================================

COMMENT ON COLUMN agent_task_records.input_tokens IS 
  'Number of tokens sent to LLM (prompt + context). Populated by agent-llm-proxy.';

COMMENT ON COLUMN agent_task_records.output_tokens IS 
  'Number of tokens generated by LLM (completion). Populated by agent-llm-proxy.';

COMMENT ON COLUMN agent_task_records.total_tokens IS 
  'Total tokens consumed (input + output). Used for cost calculation and reporting.';

COMMENT ON COLUMN agent_task_records.llm_model IS 
  'LLM model identifier (e.g., gpt-4, claude-3-opus). Populated by agent-llm-proxy.';

COMMENT ON COLUMN agent_task_records.llm_provider IS 
  'LLM provider identifier (e.g., openai, anthropic). Populated by agent-llm-proxy.';

COMMENT ON COLUMN agent_task_records.cost_usd_cents IS 
  'Task cost in USD cents (derived from actual_cost_sats using BTC/USD snapshot at completion time). NOT authoritative - actual_cost_sats is primary truth.';

COMMENT ON COLUMN agent_task_records.task_output_summary IS 
  'Punch-listed task deliverables for reporting and performance dashboards. Populated on task completion.';

COMMENT ON INDEX idx_agent_tasks_reporting IS 
  'Optimizes report queries by assignee_agent_id and completed_at. Used by agent_daily_report and agent_weekly_report views.';

-- ============================================================================
-- MIGRATION COMPLETE
-- ============================================================================

DO $$
BEGIN
  RAISE NOTICE 'Agent Task Records LLM Tracking Extension migration completed successfully';
  RAISE NOTICE 'Added columns: input_tokens, output_tokens, total_tokens, llm_model, llm_provider, cost_usd_cents, task_output_summary';
  RAISE NOTICE 'Added index: idx_agent_tasks_reporting';
END $$;

